# Generated by Django 3.0.6 on 2020-06-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORMInitiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=10, null=True)),
                ('full_name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
